#!/usr/bin/env sh

### Old script
#eval $(register-python-autocomplete ros2)
#if [ -f install/setup.bash ]; then
#    source install/setup.bash
#fi
###

_pixi_ros_shell=sh
_pixi_ros_setup=setup.sh
_pixi_ros_local_setup=local_setup.sh

if [ -n "${ZSH_VERSION:-}" ]; then
    _pixi_ros_shell=zsh
    _pixi_ros_setup=setup.zsh
    _pixi_ros_local_setup=local_setup.zsh
elif [ -n "${BASH_VERSION:-}" ]; then
    _pixi_ros_shell=bash
    _pixi_ros_setup=setup.bash
    _pixi_ros_local_setup=local_setup.bash
fi

if [ -n "$CONDA_PREFIX" ] && [ -d "$CONDA_PREFIX/bin" ]; then
    export PATH="$CONDA_PREFIX/bin${PATH:+:$PATH}"
fi

case $- in
    *i*)
        if command -v register-python-argcomplete >/dev/null 2>&1; then
            if [ "$_pixi_ros_shell" = zsh ]; then
                autoload -Uz compinit
                compinit -u
            fi
            eval "$(register-python-argcomplete --shell "$_pixi_ros_shell" ros2)"
        fi
        ;;
esac

if [ -n "$CONDA_PREFIX" ] && [ -f "$CONDA_PREFIX/$_pixi_ros_setup" ]; then
    . "$CONDA_PREFIX/$_pixi_ros_setup"
fi

_pixi_ros_sllidar_ignore="./sllidar_ros2/COLCON_IGNORE"
_pixi_ros_sllidar_ignore_reason="Generated by activate.sh on macOS: sllidar_ros2 is ignored because the current workspace does not support building this hardware driver on macOS."

if [ -d "./sllidar_ros2" ]; then
    if [ "$(uname -s)" = "Darwin" ]; then
        printf '%s\n' "$_pixi_ros_sllidar_ignore_reason" > "$_pixi_ros_sllidar_ignore"
    elif [ -f "$_pixi_ros_sllidar_ignore" ] && grep -qxF "$_pixi_ros_sllidar_ignore_reason" "$_pixi_ros_sllidar_ignore"; then
        rm "$_pixi_ros_sllidar_ignore"
    fi
fi

if [ -f "./install/$_pixi_ros_local_setup" ]; then
    if [ -n "$CONDA_PREFIX" ] && [ -x "${CONDA_PREFIX}/bin/python3" ]; then
        export COLCON_PYTHON_EXECUTABLE="${CONDA_PREFIX}/bin/python3"
        _pixi_ros_unset_colcon_python=1
    fi
    . "./install/$_pixi_ros_local_setup"
    if [ -n "${_pixi_ros_unset_colcon_python:-}" ]; then
        unset COLCON_PYTHON_EXECUTABLE
    fi
fi

unset _pixi_ros_unset_colcon_python
unset _pixi_ros_sllidar_ignore_reason
unset _pixi_ros_sllidar_ignore
unset _pixi_ros_local_setup
unset _pixi_ros_setup
unset _pixi_ros_shell
