[workspace]
authors = ["SoggyOtter <alexandere42@outlook.com>"]
channels = ["robostack-humble", "conda-forge"]
name = "und_edubot"
platforms = ["linux-64", "linux-aarch64", "osx-arm64"]
version = "0.1.0"

[tasks]
build = "colcon build --symlink-install"
format = { cmd = "ruff format src", default-environment = "test" }
typecheck = { cmd = "pyrefly check", default-environment = "test" }
zenohd = { cmd = "ros2 run rmw_zenoh_cpp rmw_zenohd", default-environment = "zenoh" }
clean = "rm -rf build install log"
pibot = "ros2 run PiBot motor_control"
teleop = "ros2 run teleop_twist_keyboard teleop_twist_keyboard"
velocity_controller = "ros2 launch PiBot PiBot_launch.py"


[dependencies]
ros-humble-foxglove-bridge = ">=0.8.5,<0.9"
ros-humble-desktop = ">=0.10.0,<0.11"
colcon-common-extensions = ">=0.3.0,<0.4"
setuptools = "<=58.2.0"
ros-humble-rmw-zenoh-cpp = ">=0.1.2,<0.2"
cxx-compiler = ">=1.11.0,<2"
cmake = "<3.27"
ninja = ">=1.13.2,<2"
pkg-config = ">=0.29.2,<0.30"
gpiozero = ">=2.0.1,<3"
numpy = ">=1.26.4,<2"
compilers = ">=1.11.0,<2"
python = ">=3.11.15,<3.12"

[feature.zenoh.activation]
env = {
    RMW_IMPLEMENTATION="rmw_zenoh_cpp",
    ZENOH_ROUTER_CONFIG_URI="$PIXI_PROJECT_ROOT/router.json5"}

[feature.test.dependencies]
ruff = "*"

[feature.test.pypi-dependencies]
pyrefly = ">=1.1.1, <2"

[environments]
zenoh = ["zenoh"]
test = ["test"]

[activation]
scripts = ["./activate.sh"]

# Should probably add this to linux-aarch64 target
[system-requirements]
libc = "2.34"

[target.linux-aarch64.dependencies]
lgpio = ">=0.2.2.0,<0.3"
smbus2 = ">=0.4.3,<0.5"
